name: Terraform Plan Workflow

on:
  workflow_dispatch

jobs:
  terraform_deployment:
    name: Deploying Terraform Modules
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Setting up Terraform
         uses: hashicorp/setup-terraform@v1

       - name: Configuring AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1

       - name: Terraform Init
         run: terraform init
         working-directory: main
        
       - name: Setup TFLint
       - uses: terraform-linters/setup-tflint@v4
         with:
          tflint_version: v0.52.0

       - name: Init TFLint
         run: tflint --init

       - name: Run TFLint
         run: tflint -f compact

       - name: Running Checkov
         uses: bridgecrewio/checkov-action@master
         with:
           directory: ./main
           quiet: true 
           soft_fail: true 
           framework: terraform 

       - name: Terraform validate
         run: terraform validate
         working-directory: main

       - name: Terraform Plan
         run: terraform plan
         working-directory: main
        